sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 206618

  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tHzX4fMjySKcCoCvYci
    access-key-secret: vPKhVa4Kux8jUP6fU4614CQ3FW0wiC
    bucket-name: cangqiongwaimaipbj

  redis:
    host: localhost
    port: 6379
    password: 206618